"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),crypto=require("node:crypto"),fs=require("node:fs"),path=require("node:path"),report=require("../assets/exposure-report"),create=require("../api/create-checkout-session"),status=require("../api/checkout-status"),webhook=require("../api/stripe-webhook");
function res(){return{statusCode:0,headers:{},setHeader(k,v){this.headers[k]=v},end(b){this.body=JSON.parse(b)}}}
function configure(){process.env.STRIPE_SECRET_KEY="sk_test_example";process.env.PUBLIC_BASE_URL="https://example.test";process.env.KV_REST_API_URL="https://kv.example.test";process.env.KV_REST_API_TOKEN="kv_token_example"}
function tokenFromCookie(header){return decodeURIComponent(/pulse_fulfillment=([^;]+)/.exec(header)[1])}
function paidSession(tokenHash,overrides={}){return{id:"cs_test_123",payment_status:"paid",livemode:false,amount_total:9900,currency:"usd",metadata:{product_id:create.PRODUCT_ID,fulfillment_token_hash:tokenHash},...overrides}}
test("reference arithmetic and escaped report",()=>{const r=report.build({organization:"<script>x</script>",preparedFor:"Diligence",asOfDate:"2026-09-14",fte:600,turnoverPercent:17.6,vacancyDays:78,replacementCost:60090,reportedAmount:5e6,additionalExposure:1e6});assert.equal(r.estimatedDepartures,105.6);assert.equal(r.vacancyFteDays,8236.8);assert.equal(r.replacementScenario,6345504);assert.equal(r.scenarioDifference,2345504);const h=report.toHtml(r);assert.doesNotMatch(h,/<script>x/);assert.match(h,/not establish actual, unrecognized, booked, reserved/);assert.throws(()=>report.build({fte:0,turnoverPercent:1,vacancyDays:1,replacementCost:1}))});
test("checkout fails closed without test secret",async()=>{const old=process.env.STRIPE_SECRET_KEY;delete process.env.STRIPE_SECRET_KEY;const s=res();await create({method:"POST",headers:{}},s);assert.equal(s.statusCode,503);if(old)process.env.STRIPE_SECRET_KEY=old});
test("checkout fixes amount and issues browser-bound HttpOnly token",async()=>{configure();const old=global.fetch;let request;global.fetch=async(u,o)=>(request={u,o},{ok:true,json:async()=>({id:"cs_test_123",url:"https://checkout.stripe.test/session",livemode:false})});const s=res();await create({method:"POST",headers:{}},s);global.fetch=old;assert.equal(s.statusCode,200);assert.match(s.headers["Set-Cookie"],/HttpOnly; Secure; SameSite=Lax; Path=\/api/);const token=tokenFromCookie(s.headers["Set-Cookie"]),body=new URLSearchParams(request.o.body);assert.equal(body.get("line_items[0][price_data][unit_amount]"),"9900");assert.equal(body.get("line_items[0][price_data][currency]"),"usd");assert.equal(body.get("metadata[fulfillment_token_hash]"),crypto.createHash("sha256").update(token).digest("hex"));assert.ok(!s.body.fulfillmentToken)});
test("fulfillment verifies amount/currency and consumes token once",async()=>{configure();const token=crypto.randomBytes(32).toString("base64url"),hash=crypto.createHash("sha256").update(token).digest("hex"),session=paidSession(hash),commands=[],old=global.fetch;global.fetch=async(u,o)=>{if(String(u).startsWith("https://api.stripe.com"))return{ok:true,json:async()=>session};const command=JSON.parse(o.body);commands.push(command);if(command[0]==="GET")return{ok:true,json:async()=>({result:JSON.stringify({sessionId:session.id,productId:create.PRODUCT_ID,amountTotal:9900,currency:"usd",paymentStatus:"paid",livemode:false,tokenHash:hash})})};return{ok:true,json:async()=>({result:"OK"})}};const s=res();await status({method:"GET",query:{session_id:session.id},headers:{cookie:`pulse_fulfillment=${token}`}},s);global.fetch=old;assert.deepEqual(s.body,{fulfilled:true,testMode:true});assert.match(s.headers["Set-Cookie"],/Max-Age=0/);assert.equal(commands.filter(c=>c[0]==="SET").length,2)});
test("session id alone and amount mismatch cannot fulfill",async()=>{configure();let s=res();await status({method:"GET",query:{session_id:"cs_test_123"},headers:{}},s);assert.equal(s.statusCode,401);const token=crypto.randomBytes(32).toString("base64url"),hash=crypto.createHash("sha256").update(token).digest("hex"),old=global.fetch;global.fetch=async()=>({ok:true,json:async()=>paidSession(hash,{amount_total:9800})});s=res();await status({method:"GET",query:{session_id:"cs_test_123"},headers:{cookie:`pulse_fulfillment=${token}`}},s);global.fetch=old;assert.equal(s.statusCode,403)});
test("claimed fulfillment token is rejected on replay",async()=>{configure();const token=crypto.randomBytes(32).toString("base64url"),hash=crypto.createHash("sha256").update(token).digest("hex"),session=paidSession(hash),old=global.fetch;global.fetch=async(u,o)=>{if(String(u).startsWith("https://api.stripe.com"))return{ok:true,json:async()=>session};const c=JSON.parse(o.body);if(c[0]==="GET")return{ok:true,json:async()=>({result:JSON.stringify({sessionId:session.id,productId:create.PRODUCT_ID,amountTotal:9900,currency:"usd",paymentStatus:"paid",livemode:false,tokenHash:hash})})};if(String(c[1]).startsWith("claim:"))return{ok:true,json:async()=>({result:null})};return{ok:true,json:async()=>({result:"OK"})}};const s=res();await status({method:"GET",query:{session_id:session.id},headers:{cookie:`pulse_fulfillment=${token}`}},s);global.fetch=old;assert.equal(s.statusCode,409)});
test("webhook rejects bad signatures and durably records valid events",async()=>{configure();process.env.STRIPE_WEBHOOK_SECRET="whsec_example";const tokenHash="a".repeat(64),event={id:"evt_test_123",type:"checkout.session.completed",data:{object:paidSession(tokenHash)}},payload=Buffer.from(JSON.stringify(event)),timestamp=Math.floor(Date.now()/1000),signature=crypto.createHmac("sha256",process.env.STRIPE_WEBHOOK_SECRET).update(`${timestamp}.`).update(payload).digest("hex"),old=global.fetch,commands=[];global.fetch=async(u,o)=>(commands.push(JSON.parse(o.body)),{ok:true,json:async()=>({result:"OK"})});let s=res();await webhook({method:"POST",headers:{"stripe-signature":"t=1,v1=bad"},body:payload},s);assert.equal(s.statusCode,400);s=res();await webhook({method:"POST",headers:{"stripe-signature":`t=${timestamp},v1=${signature}`},body:payload},s);global.fetch=old;assert.equal(s.statusCode,200);assert.ok(commands.some(c=>String(c[1]).startsWith("entitlement:")));assert.ok(commands.some(c=>String(c[1]).startsWith("stripe-event:")));assert.ok(commands.every(c=>c.includes("NX")))});
test("static surface is responsive, linked, and secret-free",()=>{const h=fs.readFileSync(path.join(__dirname,"..","service.html"),"utf8"),i=fs.readFileSync(path.join(__dirname,"..","index.html"),"utf8");assert.match(h,/name="viewport"/);assert.match(h,/@media\(max-width:720px\)/);assert.match(h,/id="download"[^>]*hidden/);assert.match(h,/api\/checkout-status/);assert.doesNotMatch(h,/sk_(test|live)_[A-Za-z0-9]{8,}/);assert.match(i,/href="service.html">Scenario report/);assert.match(i,/Open the test checkout and exposure report tool/)});
test("live Stripe key is rejected",async()=>{process.env.STRIPE_SECRET_KEY="sk_live_example";const s=res();await create({method:"POST",headers:{}},s);assert.equal(s.statusCode,503)});
