(function(root,factory){
  const api=factory();
  if(typeof module==="object"&&module.exports)module.exports=api;
  else root.PulseExposureReport=api;
})(typeof globalThis!=="undefined"?globalThis:this,function(){
  "use strict";
  const LIMITS={fte:[1,100000],turnoverPercent:[0,100],vacancyDays:[0,365],patientsPerVacancyDay:[0,10],replacementCost:[0,1000000],reportedAmount:[0,1e12],additionalExposure:[0,1e12]};
  const CHOICES={decisionContext:["credit-lending","transaction-diligence","insurance","governance","counsel","other"],dataScope:["enterprise","facility","acute-care","custom"],fteBasis:["denominator-matched-fte","enterprise-headcount-proxy","other"]};
  const LABELS={"credit-lending":"Credit / lending","transaction-diligence":"Transaction diligence",insurance:"Insurance",governance:"Governance",counsel:"Counsel",other:"Other",enterprise:"Enterprise",facility:"Facility","acute-care":"Acute care",custom:"Custom","denominator-matched-fte":"Denominator-matched FTE","enterprise-headcount-proxy":"Enterprise headcount proxy"};
  const IMPLICATIONS={
    "credit-lending":["Use the workforce decomposition to identify assumptions that warrant lender diligence; do not treat the scenario as a covenant or credit conclusion.","Request denominator-matched facility data before comparing the scenario with borrower reporting or forecasts."],
    "transaction-diligence":["Use the driver table to identify diligence questions and model sensitivities; do not treat it as a purchase-price adjustment.","Reconcile scope, period, and workforce denominator before comparing facilities or transaction cases."],
    insurance:["Use the evidence matrix to identify underwriting information gaps; do not treat any scenario as actuarial loss or expected claims.","Seek validated exposure and outcome data before considering patient-outcome implications."],
    governance:["Use the readiness rating and audit trail to frame management questions, not governance conclusions.","Prioritize consistent workforce, patient-volume, and source documentation across reporting periods."],
    counsel:["Use the decomposition to organize factual inquiry; the report does not determine negligence, causation, damages, or legal liability.","Preserve source provenance and obtain matter-specific records through an approved secure process."],
    other:["Use the report as a screening map of assumptions, sensitivities, and missing evidence, not as professional advice.","Define the intended decision and denominator before relying on comparisons."]
  };
  function numberInput(value,key){const x=Number(value),[min,max]=LIMITS[key];if(!Number.isFinite(x)||x<min||x>max)throw new Error(`${key} must be between ${min} and ${max}.`);return x}
  function text(value,max,fallback){const clean=String(value||"").replace(/\s+/g," ").trim();return(clean||fallback).slice(0,max)}
  function choice(value,key,fallback){if(!CHOICES[key].includes(value||""))throw new Error(`${key} must be one of: ${CHOICES[key].join(", ")}.`);return value||fallback}
  function normalize(value){return{organization:text(value.organization,120,"Confidential organization"),preparedFor:text(value.preparedFor,120,"Internal review"),asOfDate:/^\d{4}-\d{2}-\d{2}$/.test(String(value.asOfDate||""))?String(value.asOfDate):new Date().toISOString().slice(0,10),decisionContext:choice(value.decisionContext||"other","decisionContext","other"),dataScope:choice(value.dataScope||"custom","dataScope","custom"),fteBasis:choice(value.fteBasis||"other","fteBasis","other"),keyQuestion:text(value.keyQuestion,500,"No decision question supplied."),sourceNotes:text(value.sourceNotes,2000,"No source provenance supplied."),fte:numberInput(value.fte,"fte"),turnoverPercent:numberInput(value.turnoverPercent,"turnoverPercent"),vacancyDays:numberInput(value.vacancyDays,"vacancyDays"),patientsPerVacancyDay:numberInput(value.patientsPerVacancyDay??.5,"patientsPerVacancyDay"),replacementCost:numberInput(value.replacementCost,"replacementCost"),reportedAmount:numberInput(value.reportedAmount||0,"reportedAmount"),additionalExposure:numberInput(value.additionalExposure||0,"additionalExposure"),notes:text(value.notes,1200,"No additional non-identifying notes supplied.")}}
  function readiness(input){const documented=input.sourceNotes!=="No source provenance supplied."&&input.sourceNotes.length>=80;if(input.fteBasis==="denominator-matched-fte"&&documented)return{rating:"Stronger",reason:"The FTE basis is represented as denominator-matched and the source note is substantive; independent source verification is still required."};if(input.fteBasis==="denominator-matched-fte"||documented)return{rating:"Developing",reason:"One of the denominator or provenance conditions is stronger, but the evidence package remains incomplete."};return{rating:"Limited",reason:"The workforce denominator is a proxy or other basis and source provenance is not sufficiently documented."}}
  function build(value){
    const input=normalize(value),estimatedDepartures=input.fte*input.turnoverPercent/100,vacancyFteDays=estimatedDepartures*input.vacancyDays,replacementScenario=estimatedDepartures*input.replacementCost,combinedScenario=replacementScenario+input.additionalExposure,modeledPatientCareDays=vacancyFteDays*input.patientsPerVacancyDay,phcReportedRateSensitivity=modeledPatientCareDays*.029*24826;
    return{input,estimatedDepartures,vacancyFteDays,replacementScenario,combinedScenario,scenarioDifference:combinedScenario-input.reportedAmount,reportedComparisonAvailable:input.reportedAmount>0,modeledPatientCareDays,phcReportedRateSensitivity,mamoduleStatus:"DATA NOT SUFFICIENT",readiness:readiness(input),drivers:{departuresAvoidedPer1pp:input.fte*.01,costPer1ppTurnover:input.fte*.01*input.replacementCost,replacementCostSensitivityPer1000:estimatedDepartures*1000,patientCareDaysPer1pp:input.fte*.01*input.vacancyDays*input.patientsPerVacancyDay,patientCareDaysPer10VacancyDays:estimatedDepartures*10*input.patientsPerVacancyDay},implications:IMPLICATIONS[input.decisionContext],generatedAt:new Date().toISOString(),limitations:["This is a transparent scenario and sensitivity report, not accounting, actuarial, legal, clinical, valuation, underwriting, or causal advice.","Inputs are user supplied and require source, period, scope, and denominator verification before use.","One-driver-at-a-time sensitivities hold all other entered assumptions constant and do not represent probabilities.","The PHC layer is non-transport-validated and non-additive; it is not observed harm, booked liability, a reserve, a claim forecast, or a decision-ready estimate.","MAModule is DATA NOT SUFFICIENT and produces no mortality estimate.","Do not enter patient information, records, or other protected or confidential data."]}
  }
  function escape(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c])}
  function money(value){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value)}
  function number(value,digits){return new Intl.NumberFormat("en-US",{maximumFractionDigits:digits}).format(value)}
  function row(label,value){return`<tr><td>${escape(label)}</td><td>${value}</td></tr>`}
  function bullet(items){return`<ul>${items.map(item=>`<li>${escape(item)}</li>`).join("")}</ul>`}
  function toHtml(report){
    const i=report.input,comparison=report.reportedComparisonAvailable?`<table>${row("User-entered reported/recognized amount",money(i.reportedAmount))}${row("Scenario-to-reported arithmetic difference",money(report.scenarioDifference))}</table><p>This is an arithmetic comparison only; it does not identify a reporting gap, omitted liability, required reserve, covenant result, or accounting adjustment.</p>`:`<p><strong>Reported/recognized amount: not supplied.</strong> No scenario-to-reported difference or gap interpretation is presented.</p>`;
    const provenance=[["Nursing workforce amount",number(i.fte,1),LABELS[i.fteBasis]||i.fteBasis],["Turnover",number(i.turnoverPercent,1)+"%","User-entered rate"],["Vacancy duration",number(i.vacancyDays,0)+" days","User-entered assumption"],["Patients per vacancy day",number(i.patientsPerVacancyDay,2),"User-entered sensitivity assumption"],["Replacement cost per departure",money(i.replacementCost),"User-entered assumption"],["Additional exposure",money(i.additionalExposure),"User-entered; not inferred by PULSE"]];
    return`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PULSE Workforce Exposure Advisory Report</title><style>body{font:16px/1.58 Arial,sans-serif;color:#102725;margin:40px auto;max-width:980px;padding:0 24px}h1,h2{color:#0d3b36}h2{margin-top:36px}table{width:100%;border-collapse:collapse;margin:18px 0}th,td{padding:10px;border-bottom:1px solid #bdd0cb;text-align:left}td:last-child:not(:first-child){text-align:right}.notice{border-left:4px solid #9b792f;background:#f4f1e8;padding:16px}.matrix td:last-child{text-align:left}.tag{font-weight:bold;color:#0d3b36}small{color:#536b67}@media print{button{display:none}}</style></head><body><h1>PULSE Workforce Exposure Advisory Report</h1><p><strong>${escape(i.organization)}</strong><br>Prepared for ${escape(i.preparedFor)} · As of ${escape(i.asOfDate)}</p><div class="notice"><strong>Decision-support scenario, not professional advice.</strong> This report organizes user-supplied assumptions, arithmetic, sensitivities, evidence limits, and next-data priorities. It does not establish liability, causation, reserves, claims, accounting treatment, covenant compliance, valuation, or underwriting conclusions.</div>
    <h2>1. Executive decision brief</h2><p><strong>Question:</strong> ${escape(i.keyQuestion)}</p><p>The entered workforce assumptions produce ${number(report.estimatedDepartures,1)} annual departures, ${number(report.vacancyFteDays,1)} vacancy FTE-days, and a ${money(report.replacementScenario)} replacement-cost scenario. The central decision issue is whether the scope, denominator, period, and source record are sufficiently matched for the stated use. Current readiness is <strong>${escape(report.readiness.rating)}</strong>: ${escape(report.readiness.reason)}</p>
    <h2>2. Decision context and scope</h2><table>${row("Decision context",escape(LABELS[i.decisionContext]||i.decisionContext))}${row("Data scope",escape(LABELS[i.dataScope]||i.dataScope))}${row("Workforce basis",escape(LABELS[i.fteBasis]||i.fteBasis))}${row("Prepared for",escape(i.preparedFor))}${row("As-of date",escape(i.asOfDate))}</table>
    <h2>3. Data quality and readiness</h2><p><span class="tag">${escape(report.readiness.rating)}</span> — ${escape(report.readiness.reason)}</p><p>This rating is an internal screening signal based only on the declared FTE basis and source-note completeness. It is not an audit opinion, assurance conclusion, or standards-compliance determination.</p>
    <h2>4. Input provenance and assumptions</h2><table><tr><th>Input</th><th>Entered value</th><th>Basis</th></tr>${provenance.map(x=>`<tr><td>${escape(x[0])}</td><td>${x[1]}</td><td>${escape(x[2])}</td></tr>`).join("")}</table><p><strong>Source notes:</strong> ${escape(i.sourceNotes)}</p><p><strong>Additional notes:</strong> ${escape(i.notes)}</p>
    <h2>5. Workforce exposure decomposition</h2><p>Annual departures = nursing workforce × turnover rate. Vacancy FTE-days = annual departures × vacancy duration. Replacement-cost scenario = annual departures × replacement cost per departure. Combined user-input scenario = replacement-cost scenario + user-supplied additional exposure; PHC is excluded.</p><table>${row("Estimated annual departures",number(report.estimatedDepartures,1))}${row("Vacancy FTE-days",number(report.vacancyFteDays,1))}${row("Replacement-cost scenario",money(report.replacementScenario))}${row("Additional user-supplied exposure",money(i.additionalExposure))}${row("Combined user-input scenario",money(report.combinedScenario))}</table>
    <h2>6. Driver analysis — one factor at a time</h2><p>Each sensitivity changes one input while holding all other entered assumptions constant.</p><table>${row("Departures avoided per 1 percentage-point lower turnover",number(report.drivers.departuresAvoidedPer1pp,2))}${row("Replacement cost per 1 percentage-point turnover",money(report.drivers.costPer1ppTurnover))}${row("Replacement-cost change per $1,000 per-departure assumption",money(report.drivers.replacementCostSensitivityPer1000))}${row("Modeled patient-care days per 1 percentage-point turnover",number(report.drivers.patientCareDaysPer1pp,1))}${row("Modeled patient-care days per 10 vacancy days",number(report.drivers.patientCareDaysPer10VacancyDays,1))}</table>
    <h2>7. Base results and reported-amount comparison</h2><table>${row("Base replacement-cost scenario",money(report.replacementScenario))}${row("Combined user-input scenario",money(report.combinedScenario))}${row("Modeled patient-care days",number(report.modeledPatientCareDays,1))}</table>${comparison}
    <h2>8. PHC reported-rate sensitivity</h2><p>Formula: modeled patient-care days × 0.029 reported-event rate × $24,826 severity amount. Result: <strong>${money(report.phcReportedRateSensitivity)}</strong>.</p><p class="notice">The 2.9% and $24,826 constants are fixed model assumptions carried forward for transparent sensitivity analysis; they are not institution observations and must be source- and transport-validated for the intended use. This layer is non-additive and is never included in the combined scenario or reported-amount comparison. It is not observed harm, booked liability, a reserve, a claim forecast, or decision-ready.</p>
    <h2>9. MAModule evidence gate</h2><p><strong>${escape(report.mamoduleStatus)}</strong></p><p>No numeric mortality estimate is produced. Institution-specific denominator-matched staffing, exposure, and outcome data plus a validated causal and transport model are required.</p>
    <h2>10. Conclusion–evidence matrix</h2><table class="matrix"><tr><th>Category</th><th>Conclusion</th><th>Evidence boundary</th></tr><tr><td>Supported</td><td>Arithmetic outputs and one-factor sensitivities</td><td>Reproducible from the entered assumptions</td></tr><tr><td>Conditional</td><td>Usefulness for ${escape(LABELS[i.decisionContext]||i.decisionContext)} screening</td><td>Depends on source, period, scope, and denominator matching</td></tr><tr><td>Unavailable</td><td>Actual liability, reserve, expected claims, causation, mortality attribution, or required action</td><td>Not established by this model</td></tr></table>
    <h2>11. Decision-context implications</h2>${bullet(report.implications)}
    <h2>12. Prioritized next data and actions</h2>${bullet(["Verify workforce numerator and denominator for the stated data scope and period.","Document the source, owner, extraction date, and reconciliation for every entered assumption.","Replace scenario defaults with institution-specific vacancy-duration, patient-volume, and replacement-cost evidence.","Re-run one-driver-at-a-time sensitivities and retain the input/output record for comparison.","Escalate to qualified accounting, actuarial, legal, clinical, valuation, or underwriting professionals where the decision requires those judgments."])}
    <h2>13. Methodology and audit trail</h2><p>The report preserves normalized inputs, formula definitions, generated timestamp, source notes, and one-driver-at-a-time sensitivities so another reviewer can reproduce the arithmetic. Its presentation is informed by the IFRS Conceptual Framework qualities of relevance, faithful representation, comparability, verifiability, and understandability, and by GAO cost-estimating guidance on traceable assumptions and sensitivity analysis. This is an alignment aid, not a claim of IFRS, GAAP, GAO, audit, assurance, or regulatory compliance.</p><p>Official references: <a href="https://www.ifrs.org/content/dam/ifrs/publications/pdf-standards/english/2021/issued/part-a/conceptual-framework-for-financial-reporting.pdf">IFRS Conceptual Framework for Financial Reporting</a>; <a href="https://www.gao.gov/products/gao-09-3sp">GAO Cost Estimating and Assessment Guide (GAO-09-3SP)</a>.</p><table>${row("Generated",escape(report.generatedAt))}${row("Formula version","PULSE workforce exposure v2")}${row("PHC constants","0.029 and $24,826")}${row("Reported comparison produced",report.reportedComparisonAvailable?"Yes":"No")}</table>
    <h2>14. Limitations</h2>${bullet(report.limitations)}<p><small>Generated ${escape(report.generatedAt)} · PULSE Advisory Group.</small></p><button onclick="window.print()">Print / save as PDF</button></body></html>`;
  }
  return{LIMITS,normalize,build,toHtml,money,number};
});
